In [32]:
import pandas as pd

data = pd.read_csv('pm10_data.csv', encoding='cp949')
df = pd.DataFrame(data)

In [33]:
# column명에서 '월' 제거
df.columns = df.columns.str.replace('월', '').str.strip()

# 쓸모 없는 column drop
df = df.drop(columns=['항목', '단위'])

# 가로형 데이터를 세로형(표준 형태)으로 변환
df_long = df.melt(id_vars=['구분'],
                  var_name='YearMonth',
                  value_name='PM10')

df_long.head()

      구분 YearMonth  PM10
0     총계   2010.01  57.0
1  서울특별시   2010.01  59.0
2  부산광역시   2010.01  47.0
3  대구광역시   2010.01  56.0
4  인천광역시   2010.01  64.0

In [34]:
# 날짜 형식을 분기(Quarter)로 변환
df_long['Quarter'] = pd.to_datetime(df_long['YearMonth'], format='%Y.%m', errors='coerce').dt.to_period('Q')

# 지역 및 분기별 집계
df_long['PM10'] = df_long['PM10'].astype(str).str.replace(r'\*+', '', regex=True)
df_long['PM10'] = pd.to_numeric(df_long['PM10'], errors='coerce')

df_quarterly = df_long.groupby(['구분', 'Quarter'])['PM10'].mean().reset_index()
df_quarterly['PM10'] = df_quarterly['PM10'].round(2)
df_quarterly.head()

   구분 Quarter  PM10
0  가평  2010Q1   NaN
1  가평  2010Q2   NaN
2  가평  2010Q3   NaN
3  가평  2010Q4   NaN
4  가평  2011Q1  69.0

In [38]:
import matplotlib.pyplot as plt
print(df_long['구분'].unique())

<ArrowStringArray>
[     '총계',   '서울특별시',   '부산광역시',   '대구광역시',   '인천광역시',   '광주광역시',   '대전광역시',
   '울산광역시', '세종특별자치시',      '수원',
 ...
      '거창',      '함안',      '함양',      '남해',      '산청',      '의령',      '창녕',
      '합천',      '제주',     '서귀포']
Length: 166, dtype: str